---
title: "Türkiye’de COVID-19 pandemisinin toplumun mutluluğu üzerindeki etkisi"
author: 
  - Ömer Yiğit Kaya[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
abstract: |
 Bu çalışmada, Covid-19 pandemisinin Türkiye'deki bireylerin mutluluk düzeyi üzerindeki etkisini incelemek amaçlanmıştır. Bu doğrultuda TÜİK'in Merkezi Dağıtım Sistemi'nden toplanan veri seti kullanılmıştır. Verilerin incelenmesi sırasında korelasyon analizi ve Dörtlü Korelasyon Katsayısı yöntemlerinin kullanılması planlanmıştır; ancak, verilerin işlenmesi sırasında yaşanan zorluklar nedeniyle bu yöntemlerle elde edilen sonuçlar tablolara aktarılamamıştır. Bu çalışma, Covid-19'un bireylerin mutluluk düzeyi üzerindeki etkisini istatistiksel bir perspektiften araştırmaktadır.
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080371, [Github Repo](https://github.com/omeryigitkaya/istatistik-final-odev-)

# Giriş

Covid-19, 2019 yılı sonunda Çin'in Wuhan kentinde ortaya çıkan ve kısa sürede tüm dünyaya yayılan yeni tip bir koronavirüs hastalığıdır. Dünya Sağlık Örgütü tarafından pandemi ilan edilen Covid-19, insan sağlığı, ekonomi, eğitim, sosyal hayat gibi pek çok alanda ciddi sorunlara neden olmuştur. Covid-19 salgını, bireylerin yaşam koşullarını, ruh sağlığını ve mutluluk düzeylerini de etkilemiştir.

[@bakkeli2021health]'nin araştırmış olduğu **Norveç'te Covid-19 salgını öncesinde ve sırasında mutluluk düzeyi** isimli çalışmayı Türkiye'ye uyarlamak istedim.Bunun için başlangıçta [@karatacs2020covid] [@gungorer2020covid] [@ustun2020covid]'nin hazırlamış olduğu makaleleri okuyarak bilgi edindim daha sonrasında [@marzana2022community] detay bilgi ve bu konu hakkında doğru veriyi nereden toplayabilirim onu kavramaya çalıştım.

Veri setini, genel mutluluk düzeyi, kişisel sağlıktan duyulan memnuniyet ve sosyal hayattan duyulan memnuniyet olacak şekilde, TÜİK'e ait **Merkezi Dağıtım Sisteminden** edindim.Veri setinde cinsiyet, memnuniyet düzeyi (çok mutlu, mutlu, orta, mutsuz, çok mutsuz) ve verinin toplandığı yıl(2018,2019,2020,2021,2022) gibi gözlemler bulunmaktadır.

Covid-19 salgını ve onun yanında getirdiği tüm etkilerin, toplumun mutluluğu üzerindeki etkilerini incelemek için veri setinde yer alan 2018 ve 2019 verilerini Covid-19 **öncesi**, 2020 ve 2021 verilerini Covid-19 **sırası**, 2022 verisini ise Covid-19 **sonrası** olarak inceleyeceğim.


Proje ödevinizde yer alan başlıkların bu metinde yer alan başlıkları kesinlikle içermesi gerekmektedir. Burada kullanılan başlıklar haricinde farklı alt başlıklar da kullanabilirsiniz. Projenizi yazarken bu dosyayı taslak olarak kullanıp içeriğini projenize uyarlayınız.

## Çalışmanın Amacı

Covid-19 salgını, tüm dünyada insanların yaşam koşullarını, ruh sağlığını ve mutluluk düzeylerini etkileyen önemli bir olaydır. Salgın nedeniyle bireylerin karşılaştıkları korku, belirsizlik, kısıtlama, yalnızlık, işsizlik, yoksulluk gibi olumsuz durumlar, depresyon, anksiyete, stres gibi psikolojik sorunlara yol açabilir. Bu da bireylerin yaşam doyumunu ve mutluluklarını azaltabilir. Bu nedenle salgının bireylerin mutluluk düzeyi üzerindeki etkisini araştırmak hem akademik hem de sosyal açıdan önemlidir.

Bu çalışmanın amacı, Covid-19 salgınının Türkiye'deki bireylerin mutluluk düzeyi üzerindeki etkisini istatiksel olarak incelemektir. Bu amaçla bireylerin mutluluk düzeyleri ile kişisel sağlıktan duyulan memnuniyet ve sosyal hayattan duyulan memnuniyet arasındaki ilişki analiz edilecektir.

Bu çalışmanın önemi, Covid-19 salgınının bireylerin mutluluk düzeyi üzerindeki etkisini ortaya koymasıdır.

## Literatür 

Öncelikle [@marzana2022community] makalesinden yola çıkarak Covid-19’un ilk yılının, yani Türkiye için 2020 yılının **balayı** aşaması olduğunu, bireylerin toplumdan soyutlanmaya adapte olmaya çalıştığını; 2021 yılının ise **depresif** tepkinin yüksek olduğu yıl olduğunu varsayıyoruz. Bu varsayımın doğruluğunu test etmek için veri setimizde genel mutluluk düzeyinin 2020 yılında 2021 yılından daha yüksek olması gerekiyor. [@bakkeli2021health] araştırmasına göre Norveç’te **kişisel sağlıktan duyulan memnuniyet** ile **genel mutluluk** düzeyi arasında negatif bir ilişki bulunmuş. [@gungorer2020covid] makalesi de Türkiye için bu sonucu doğruluyor. [@marzana2022community] çalışması gibi [@karatacs2020covid]'in çalışması da Covid-19’un etkilerinin ağır hissedildiği iki yılın ardından toplumun **genel mutluluk** düzeyinin arttığını ele alıyor.

# Veri 

Bu çalışmada kullanılan veri seti, TÜİK'in **Merkezi Dağıtım Sistemi** üzerinden alınmıştır. Veri setindeki bazı bilgiler, CSV formatına uygun olması için sadeleştirilmiştir. Genel mutluluk kavramı, sosyal yaşamdan duyulan memnuniyet ve kişisel sağlıkla ilgili memnuniyet üzerinden değerlendirilmiştir.

# Yöntem ve Veri Analizi

[@bakkeli2021health] ve [@gungorer2020covid] çalışmalarında olduğu gibi ben de kendi çalışmamda korelasyon analizi ve Dörtlü Korelasyon Katsayısı yöntemlerini kullanmayı planladım. Covid-19 pandemisi sürecinde Türkiye'deki Covid-19 hasta sayısı ile toplumun genel refahı arasındaki korelasyonu belirlemek amaçlandı. Ancak, elde ettiğim verileri işlemekyemediğim için sonuçları tablolara yansıtamadım.

$$
r_{xy} = \frac{\sum_{i=1}^{n} (x_{i} - \bar{x})(y_{i} - \bar{y})}{\sqrt{\sum_{i=1}^{n} (x_{i} - \bar{x})^{2} (y_{i} - \bar{y})^{2}}}
$$
$$
r_{\text{ff}} = \frac{(ad - bc)}{\sqrt{(a + b)(c + d)(a + c)(b + d)}}
$$
# Sonuç

Bu çalışmaya göre, **2020** yılında Covid-19 pandemisi genel mutluluk düzeyini ve kişisel sağlıktan duyulan memnuniyeti arttırırken, sosyal hayattan duyulan memnuniyeti azaltmıştır. **2021** yılında ise genel mutluluk düzeyi düşmüş; kişisel sağlıktan duyulan memnuniyet ve sosyal hayattan duyulan memnuniyet azalmıştır. Covid-19 pandemisi sonrası olarak değerlendirdiğimiz **2022** yılında genel mutluluk düzeyi yükselmiş; kişisel sağlıktan duyulan memnuniyet ve sosyal hayattan duyulan memnuniyet artmıştır. Bu değerler, Covid-19 pandemisi **öncesindeki değerlerin de üstüne çıkmıştır**.
Bu çalışmada verilerin düzgün şekilde işlenememesi ve tablolara yansıtılamaması nedeniyle çalışma tamamlanamamıştır. Bu eksikliğin giderilmesi, çalışmayı daha anlamlı ve kapsamlı hale getirecektir.




\newpage
# Kaynakça {#references}
<div id="refs"></div>

